### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Lichtsinnig** [0xrawsec/gene#1]
Hello!
When I run the program (windows-v1.2.tar.gz), I get an error: The system can not find the path specified.
What am I doing wrong?

Rule:
`{
	"Name": "Mimikatz",
	"Tags": ["test"],
	"Meta": {
		"EventIDs": [4107],
		"Channels": ["Microsoft-Windows-PowerShell/Operational"],
		"Computers": [],
		"Criticality": 0
		},

	"Matches": [
		"$a: ScriptBlockText ~= 'Mimikatz'"
		],
	"Condition": "$a"
	}
{
	"Name": "sysmon",
	"Tags": ["sysmon"],
	"Meta": {
		"EventIDs": [1],
		"Channels": ["Microsoft-Windows-Sysmon/Operational"],
		"Computers": [],
		"Criticality": 0
		},

	"Matches": [
		"$a: Hashes ~= 'SHA256=30879AAB3ED2518FF7'"
		],
	"Condition": "$a"
	}`
Error:

`f:\>gene-386.exe -r evtx.txt "c:\windows\System32\Winevt\Logs\Microsoft-Windows-
PowerShell/Operational.evtx"
2018/03/20 19:08:15 INFO - Loaded 2 rules
2018/03/20 19:08:15 INFO - Processing: c:\windows\System32\Winevt\Logs\Microsoft
-Windows-PowerShell/Operational.evtx
2018/03/20 19:08:15 ERROR - open c:\windows\System32\Winevt\Logs\Microsoft-Windo
ws-PowerShell/Operational.evtx: The system cannot find the path specified.
2018/03/20 19:08:15 INFO - Count Event Scanned: 0
2018/03/20 19:08:15 INFO - Count Rules Used (loaded + generated): 2

f:\>gene-386.exe -r evtx.txt "%SystemRoot%\System32\Winevt\Logs\Microsoft-Window
s-PowerShell%4Operational.evtx"
2018/03/20 19:10:36 INFO - Loaded 2 rules
2018/03/20 19:10:36 INFO - Processing: C:\Windows\System32\Winevt\Logs\Microsoft
-Windows-PowerShell%4Operational.evtx
2018/03/20 19:10:36 ERROR - open C:\Windows\System32\Winevt\Logs\Microsoft-Windo
ws-PowerShell%4Operational.evtx: The system cannot find the path specified.
2018/03/20 19:10:36 INFO - Count Event Scanned: 0
2018/03/20 19:10:36 INFO - Count Rules Used (loaded + generated): 2

f:\>gene-386.exe -r evtx.txt "%SystemRoot%\System32\Winevt\Logs\Microsoft-Window
s-Sysmon%4Operational.evtx"
2018/03/20 19:11:28 INFO - Loaded 2 rules
2018/03/20 19:11:28 INFO - Processing: C:\Windows\System32\Winevt\Logs\Microsoft
-Windows-Sysmon%4Operational.evtx
2018/03/20 19:11:28 ERROR - open C:\Windows\System32\Winevt\Logs\Microsoft-Windo
ws-Sysmon%4Operational.evtx: The system cannot find the path specified.
2018/03/20 19:11:28 INFO - Count Event Scanned: 0
2018/03/20 19:11:28 INFO - Count Rules Used (loaded + generated): 2

f:\>gene-386.exe -r evtx.txt "%SystemRoot%\System32\Winevt\Logs\Microsoft-Window
s-Sysmon%4Operational.evtx" -d
2018/03/20 19:12:56 INFO - Loaded 2 rules
2018/03/20 19:12:56 INFO - Processing: C:\Windows\System32\Winevt\Logs\Microsoft
-Windows-Sysmon%4Operational.evtx
2018/03/20 19:12:56 ERROR - open C:\Windows\System32\Winevt\Logs\Microsoft-Windo
ws-Sysmon%4Operational.evtx: The system cannot find the path specified.
2018/03/20 19:12:56 INFO - Processing: -d
2018/03/20 19:12:56 ERROR - open -d: The system cannot find the file specified.
2018/03/20 19:12:56 INFO - Count Event Scanned: 0
2018/03/20 19:12:56 INFO - Count Rules Used (loaded + generated): 2`

**Comment by qjerome** [comment]
Hi, 

Quick question, do you run the program on 32bit system or 64bit?

Cheers,

**Comment by Lichtsinnig** [comment]
The operating system is 64 bit. Run the applications both 32 and 64. In both cases, the error

**Comment by Lichtsinnig** [comment]
f:\>gene-amd64.exe "%SystemRoot%\System32\Winevt\Logs\Microsoft-Windows-PowerShell%4Operational.evtx" -r evtx.txt  -d
2018/03/21 10:55:56 ERROR - No rule file to load

**Comment by Lichtsinnig** [comment]
Thanks, understood the error

**Comment by qjerome** [comment]
Did you make it work fine?

**Comment by Lichtsinnig** [comment]
The program is sensitive to the location of the parameters, in this was an error
