### ISSUE TITLE
Make fails when shell doesn't have $GOPATH

### ISSUE THREAD

**Issue by esskayesss** [0xrawsec/gene#13]
https://github.com/0xrawsec/gene/blob/4401b38e4e48b366279380f2e39f0fe5f3eecbd9/gene/makefile#L1

`go env GOPATH` shows the correct value for $GOPATH, however, on shells like mine, `echo $GOPATH` simply returns a blank line because it's not set. The makefile, if possible, could pull the value from `go env GOPATH` instead of querying the shell. 
I encountered this problem while developing a PKGBUILD. Users of my PKGBUILD will [potentially face the same issues](https://stackoverflow.com/questions/54372880/although-gopath-is-set-echo-gopath-returns-nothingl).
Please consider fixing it. For the time being, I will export the path to the installing shell.
Here's the output of `./build.sh`
```
./build.sh
go get -u github.com/0xrawsec/gene
go get -u github.com/0xrawsec/golang-evtx
go get -u github.com/0xrawsec/golang-utils
printf "package main\n\nconst(\n    version=\"1.6.13\"\n    commitID=\"4401b38e4e48b366279380f2e39f0fe5f3eecbd9\"\n)\n" > version.go
make clean
make[1]: Entering directory '.../gene/gene'
rm -rf /release/*
make[1]: Leaving directory '.../gene/gene'
make init
make[1]: Entering directory '.../gene/gene'
mkdir -p /release
mkdir: cannot create directory ‘/release’: Permission denied
make[1]: *** [makefile:21: init] Error 1
make[1]: Leaving directory '.../gene/gene'
make: *** [makefile:14: all] Error 2
```

**Comment by qjerome** [comment]
Hey @esskayesss,

I will push a new version soon and this request will be taken into account.

**Comment by qjerome** [comment]
@esskayesss be careful, there was a major version bump so the current engine will not support older rules.
You can use scripts/migraterule.py to migrate a old rule to the new rule format.

**Comment by esskayesss** [comment]
@qjerome thanks for the heads up!
